QUESTIONS_JSON_PATH = "data/questions.json"
DEFAULT_NUMBER_OF_QUESTIONS = 33
LANGUAGE_SELECTION = True
TOPIC_SELECTION = True
QUESTION_NUMBER_SELECTION = True
CORRECT_ANSWER_WEIGHT = 1
WRONG_ANSWER_WEIGHT = 0.5
